-- Fix: Update demo user password hashes to correct BCrypt hash for Demo@12345
-- Real BCrypt hash generated by Spring's BCryptPasswordEncoder (cost=10)
-- Password: Demo@12345

USE smart_krishi;

UPDATE users 
SET password_hash = '$2a$10$brlVVU/5xwlmuYJO5Lu2Le3Szu0kvbZK0cxkz/LCthSh/cky/vBAi'
WHERE email LIKE '%.demo@smartkrishi.test';

-- Verify update
SELECT email, 
       CASE WHEN password_hash = '$2a$10$brlVVU/5xwlmuYJO5Lu2Le3Szu0kvbZK0cxkz/LCthSh/cky/vBAi' 
            THEN 'HASH_OK' 
            ELSE 'HASH_BAD' 
       END AS hash_status,
       user_status
FROM users 
WHERE email LIKE '%.demo@smartkrishi.test';

-- Cleanup the temp user used to generate the hash
DELETE FROM users WHERE email = 'hashgen.temp@smartkrishi.test';
